FROM apache/airflow:2.8.2-python3.11

USER root
RUN apt-get update && \
    apt-get install -y build-essential gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

# Copy all project files
COPY . /opt/airflow/
COPY init-airflow.sh /

WORKDIR /opt/airflow

# Install the rest of the dependencies
RUN pip install --no-cache-dir .

ENV AIRFLOW_HOME=/opt/airflow