services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER_E}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_E}
      POSTGRES_DB: ${POSTGRES_DB_E}
    networks:
      - gdd_internal
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER_E}:${POSTGRES_PASSWORD_E}@postgres/${POSTGRES_DB_E}
      AIRFLOW_ADMIN_USER: ${AIRFLOW_ADMIN_USER}
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
    depends_on:
      - postgres
    entrypoint: ["/init-airflow.sh"]
    networks:
      - gdd_internal


  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER_E}:${POSTGRES_PASSWORD_E}@postgres/${POSTGRES_DB_E}
    depends_on:
      - postgres
      - airflow-init
    ports:
      - "8080:8080"
    networks:
      - gdd_internal
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER_E}:${POSTGRES_PASSWORD_E}@postgres/${POSTGRES_DB_E}
    depends_on:
      - postgres
      - airflow-init
    networks:
      - gdd_internal
    command: scheduler


  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    networks:
      - gdd_internal
    depends_on:
      - airflow-webserver

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    networks:
      - gdd_internal
    depends_on:
      - fastapi

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        NGINX_ALLOWED_ADMIN_IP_1: ${NGINX_ALLOWED_ADMIN_IP_1}
        NGINX_ALLOWED_ADMIN_IP_2: ${NGINX_ALLOWED_ADMIN_IP_2}
    depends_on:
      - streamlit
      - fastapi
      - airflow-webserver 
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gdd_internal

networks:
  gdd_internal:
    driver: bridge
    name: gdd_internal_net

volumes:
  postgres_data: