FROM apache/airflow:2.8.2-python3.11

USER root
RUN apt-get update && \
    apt-get install -y build-essential gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

# Copy all project files
COPY . /opt/airflow/
WORKDIR /opt/airflow

# Copy the init script
COPY init-airflow.sh /init-airflow.sh

# Install dependencies
RUN pip install .

ENV AIRFLOW_HOME=/opt/airflow


