FROM nginx:1.28-alpine

# Copy nginx config template.
COPY nginx/nginx.conf.template /etc/nginx/templates/nginx.conf.template

# On startup, envsubst to substitute the IP variables into the nginx.conf.
ENTRYPOINT [ "sh", "-c" ]
CMD ["envsubst '$$NGINX_ALLOWED_ADMIN_IP_1 $$NGINX_ALLOWED_ADMIN_IP_2' \
     < /etc/nginx/templates/nginx.conf.template \
     > /etc/nginx/conf.d/default.conf \
   && exec nginx -g 'daemon off;'"]