[project]
name = "gdd-app"
version = "0.1.0"
description = "Plant growth timing system for farmers using weather data from Yr.no and Growing Degree Days."
authors = [
    {name = "Eveliina Hampus",email = "eveliinahampus@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "streamlit (>=1.44.1,<2.0.0)",
    "numpy (>=2.2.5,<3.0.0)",
    "airflow (>=0.6,<0.7)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
