[project]
name = "gdd-app"
version = "0.1.0"
description = "Plant growth timing system for farmers using weather data from Yr.no and Growing Degree Days."
authors = [
    {name = "Eveliina Hampus",email = "eveliinahampus@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "streamlit (>=1.44.1,<2.0.0)",
    "numpy (>=2.2.5,<3.0.0)",
    "apache-airflow (>=3.0.0,<4.0.0)",
    "requests (>=2.32.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

