name: Trivy Container Image Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '15 8 * * 2' 

permissions:
  contents: read

jobs:
  scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up image list
        id: set-images
        run: |
          echo "DOCKERFILES=Dockerfile.fastapi Dockerfile.streamlit" >> $GITHUB_ENV

      - name: Build & Scan all images
        run: |
          mkdir -p trivy-results
          for file in $DOCKERFILES; do
            tag="scan-${file##*.}-${GITHUB_SHA}"
            docker build -f $file -t $tag .
            trivy image --format template --template "@/contrib/sarif.tpl" \
              --output "trivy-results/${tag}.sarif" \
              --severity CRITICAL,HIGH $tag
          done

      - name: Upload all SARIF reports
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results/scan-fastapi-${{ github.sha }}.sarif

     # - name: Upload additional SARIF (NGINX)
     #    uses: github/codeql-action/upload-sarif@v3
     #   with:
    #     sarif_file: trivy-results/scan-nginx-${{ github.sha }}.sarif

      - name: Upload additional SARIF (Streamlit)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results/scan-streamlit-${{ github.sha }}.sarif

    #  - name: Upload additional SARIF (Airflow)
    #     uses: github/codeql-action/upload-sarif@v3
    #    with:
    #     sarif_file: trivy-results/scan-airflow-${{ github.sha }}.sarif
