name: Trivy IaC Scan

on:
  push:
    paths:
      - 'terraform/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'terraform/**'
    branches: [ "main" ]
  schedule:
    - cron: '35 8 * * 2' 

permissions:
  contents: read

jobs:
  iac-scan:
    name: IaC Scan – Terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy IaC scan on Terraform folder
        uses: aquasecurity/trivy-action@v0.11.2
        with:
          scan-type: 'config'
          scan-ref: 'terraform'
          format: 'sarif'
          output: 'trivy-iac-results.sarif'

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-iac-results.sarif'
